platform :ios, '7.0'

pod 'CYLTabBarController'
pod 'AFNetworking'
pod 'SDWebImage'
pod 'SVProgressHUD'
pod 'MJExtension'
pod 'MJRefresh'
pod 'SDCycleScrollView'
#pod 'TMCache', '~> 2.1.0'
pod 'IQKeyboardManager'
pod 'LKDBHelper'
pod 'NJKWebViewProgress'
pod 'JCAlertView'
